### PR TITLE
Removing proportion_asymptomatic/asymp_rate as a parameter

### PR DESCRIPTION
**Pull request by spoonerf**
Now just have it configured by age:

Under 20 =  79% asymp
20-69 = 55% asymp
70+ = 33% asymp

Based on Fig 3a https://www.nature.com/articles/s41591-020-0962-9

### CODE REVIEW

**Comment by nickmalleson** [comment]
@spoonerf it looks like there's a conflict with the versio of `params.py` on the master branch. It's easy to resolve, want me to update it so that your copy takes priority? The only thing I wasn't sure about was that the indices in the arrays have changed so I wanted to check you're happy that your version is OK.

**Comment by spoonerf** [comment]
Hi @nickmalleson Yep that would be great if you could, just had to reduce a lot of the indices by one to make up for removing the proportion_asymptomatic one going. Pretty sure they're okay.

**Comment by nickmalleson** [comment]
@spoonerf I resolved the conflicts but it looks like it has failed a test. I may have done something wrong. Could you pull the new version of the `remove_asymp_prop` branch  and see if it works OK for you locally?

**Comment by spoonerf** [comment]
Hi @nickmalleson I think params.py indexing was still based on the old mortality data. Have updated now so hopefully it will pass that test.

**Comment by spoonerf** [comment]
@nickmalleson Should be okay now - not sure why the codecov is unhappy though!

**Comment by nickmalleson** [comment]
Thanks @spoonerf I'll merge now as the tests are passing. @Sparrow0hawk could you have a look at the  codecov error when you get a chance on Thursday? No rush.

**Comment by Sparrow0hawk** [comment]
Hi @nickmalleson this check has fialed because the projects overall coverage has decreased slightly (-0.04%) with this commit, it's nothing major to worry about in this circumstance!

**Pull request merged**
