### PR TITLE
Updated hazard kernel function

### PR DESCRIPTION
**Pull request by cshenton**
- Updated the hazard function in the opencl code to be `1.0-exp(-hazard*dt)` where the `dt` is implicitly `1.0`.
- Updated the corresponding test

### CODE REVIEW

**Review by rory-improbable — APPROVED** [review]
Looks good to me, although it would be good for @spoonerf or @jabrams23 to have a look at this.

Also I wonder if it's worth adding something to the docs or model design somewhere to explain this function and capture some of the discussion we had about it?

**Review by spoonerf — APPROVED** [review]
Looks great to me!

**Comment by jabrams23** [comment]
looks correct to me too

**Comment by cshenton** [comment]
@nickmalleson feel free to merge if you're happy with the change 👍

**Pull request merged**
