### PR TITLE
Examples of model in colab notebook

### PR DESCRIPTION
**Pull request by Sparrow0hawk**
This is a draft PR that will address #185 and running the model in a Colab notebook.

Currently the notebook `examples/colab/ramp-colab.ipynb` should work, although runs very slowly on the initialisation step. I also cannot get it to run on the colab GPUs which I think relates to issues with openCL drivers.

TODO:
- [x] migrate environment setup into a .sh file that is run on start up
- [x] work out how to install the correct openCL drivers
- [x] Can we speed up initialisation? Use a generic cache file?
- [ ] Sign off from other users

Have a play 👇 
https://colab.research.google.com/github/Sparrow0hawk/RAMP-UA/blob/examples-section/examples/colab/ramp-colab.ipynb

### CODE REVIEW

**Comment by rory-improbable** [comment]
@Sparrow0hawk great work on this! It's awesome to be able to run this in Colab.

Regarding the initialisation step, it looks like it is not reading from the cache, so it has have to re-convert the snapshot which takes a few minutes. Possibly a better approach is to avoid running the `main.py` function entirely, this way we can just run the OpenCL model in headless mode directly and explicitly load a snapshot file, without worrying about the cache or generating a snapshot. This is how we've done it in the other jupyter notebooks, see  [./experiments/analyse_opencl_results.ipynb](https://github.com/Urban-Analytics/RAMP-UA/blob/master/experiments/analyse_opencl_results.ipynb) which uses the `_run_opencl_model()` function in [./experiments/functions.py](https://github.com/Urban-Analytics/RAMP-UA/blob/master/experiments/functions.py). I would suggest you could just use this function to run the model, or just copy the contents of the function, just copying the contents might be a good idea since it makes it a bit more explicit and less "magic" in terms of what is actually going on. 

In the existing notebooks we are calling that function using the multiprocessing `starmap` function so we run multiple versions at once, however I suggest we avoid that in this colab example to keep it simple, so we can just call the `_run_opencl_model()` function or the equivalent code once.

It might also be worth adding some simple plots of the output data, similar to what we have in the notebooks in the experiments folder, however we can always just add this after the fact once this PR is merged.

Also regarding using the GPUs in colab, this would have been awesome but I'm not surprised it didn't work. Just out of curiosity I'd be interested to have a look at this myself so perhaps once we get this PR merged I can have a look at getting OpenCL running on colab GPUs, since this would potentially be quite useful for everyone to be able to access a GPU easily to run the model.

**Comment by rory-improbable** [comment]
I did some quick googling and it looks like there should be a way to install NVIDIA OpenCL drivers, it looks like the first block in  [this notebook](https://colab.research.google.com/github/ShimaaElabd/CUDA-GPU-Contrast-Enhancement/blob/master/CUDA_GPU.ipynb#scrollTo=mgH5HreZ2WS9 ) ends up installing some opencl dependencies, not sure if you tried anything like this:

**Comment by Sparrow0hawk** [comment]
@rory-improbable to achieve the `_run_opencl_model()` approach like your other notebooks i'd still need a snapshot file, which is something we don't include within the github repo. Is that something we could add/have available from an alternate url that I could fetch for the colab notebook?

I did have a quick go at installing the drivers via some stackoverflow suggestions but to no avail. Can't remember if I did that one specifically but will try.

**Comment by rory-improbable** [comment]
Ahh yes of course, I forgot that we were git ignoring the snapshots. The snapshot files are quite large (~170MB), but I reckon it wouldn't be a bad idea to add them to git using git LFS, then we could download the snapshot file rather than re-generating it. 

What do you reckon? I don't have strong opinions either way, I would say it's fine to just leave it as it is now and re-generate the snapshot every time, however I probably have a weak preference for adding the snapshot file using git LFS.

If we do add the snapshot file we should probably call it `default.npz` or something like that, to distinguish it from the normal cache file, then we could maybe still git ignore the `cache.npz`, since we don't want to have to commit changes to that every time it changes.

Anyway your call, whatever you think is best.

**Comment by Sparrow0hawk** [comment]
@rory-improbable I'd say i'm leaning towards having a `default.npz` file which can be used. I'll generate one and have a think about where's best to put it.

**Comment by Sparrow0hawk** [comment]
Right I think i've managed to solve GPU-related things. Issue was the conda environment not looking for system installed openCL drivers, installing the `ocl-icd-system` package resolved this.

I've also created a `default.npz` cache file that is fetched from a [zenodo repository](https://zenodo.org/record/4153512#.X5r_DVCnyUk)

Environment setup takes abit of time ~5min but then everything runs in the notebook.

@rory-improbable fancy giving it a spin?
https://colab.research.google.com/github/Sparrow0hawk/RAMP-UA/blob/examples-section/examples/colab/ramp-colab.ipynb

**Review by nickmalleson — COMMENTED** [review]
This is great @Sparrow0hawk ! I'm getting an error on the second chunk (`
ModuleNotFoundError: No module named 'microsim'`) but I've not bothered flagging it as I think it's still under development. I found the initialisation/install script really useful to see how to get a machine set up ready to run the code.

**Comment by Sparrow0hawk** [comment]
@nickmalleson This is my bad, I foolishly deleted the `examples-section` branch from this repository (as i've been doing the work for this via my fork of this repository) but that is the exact branch my install script uses! 

It should now work without erroring, although I will migrate this to using master in the final merge.

**Comment by nickmalleson** [comment]
> @nickmalleson This is my bad, I foolishly deleted the `examples-section` branch from this repository (as i've been doing the work for this via my fork of this repository) but that is the exact branch my install script uses!
> 
> It should now work without erroring, although I will migrate this to using master in the final merge.

It's still not working for me @Sparrow0hawk . It seems to install fine but then:

```
ModuleNotFoundError                       Traceback (most recent call last)

<ipython-input-1-75726155f73f> in <module>()
      7 import matplotlib.pyplot as plt
      8 
----> 9 from microsim.opencl.ramp.run import run_headless
     10 from microsim.opencl.ramp.snapshot_convertor import SnapshotConvertor
     11 from microsim.opencl.ramp.snapshot import Snapshot

ModuleNotFoundError: No module named 'microsim'
```
You may be aware, I just mention it incase.

**Comment by Sparrow0hawk** [comment]
@nickmalleson you still get this error after running the second code cell with:

```python
import sys
sys.path.append('/usr/local/lib/python3.6/site-packages')
```
As I can't replicate this error on colab myself.

**Comment by nickmalleson** [comment]
> @nickmalleson you still get this error after running the second code cell with the contents:
> 
> ```python
> import sys
> sys.path.append('/usr/local/lib/python3.6/site-packages')
> ```
> 
> As I can't replicate this error on colab myself.

That's really weird. I activate the first two cells (the curl one and then the sys one) but then the third cell gives me the error. Think I'm doing something wrong? I've not used collab before

**Comment by nickmalleson** [comment]
(I merged anyway as if it's working for you it's probably user error on my part!)

**Pull request merged**
