### PR TITLE
Add progress bars to downloading

### PR DESCRIPTION
**Pull request by dabreegster**
This PR refactors some of the code used to download files during initialization. It adds progress bars, which are particularly reassuring on that 2GB file on slow connections:
Screenshot from 2021-12-16 17-36-41

I also needed to move the two `main.py` files out of the `coding` directory to get things to run at all. See the commit message for details there. I'm curious how people have been getting it to work otherwise?

### CODE REVIEW

**Comment by nickmalleson** [comment]
Thanks @dabreegster this is definitely a useful addition. I'm not really familiar with the EcoTwins version of the code; @HSalat or @mfbenitezp would it be better for you to review and approve the merge? Only the `main` branch has restrictions on who can merge to it (which can be taken off at any time by the way, they are mostly there to limit accidents).

**Comment by dabreegster** [comment]
Hadrien and Fernando are still out on holiday, to my knowledge. I'll hold onto this until then. I am still puzzling through why there are so many branches off `master` that've diverged so far; any recent project history would be helpful!

**Comment by nickmalleson** [comment]
Afraid I can't comment on all the different ecotwins branches, but we decided to make the ecotwins work separate from the orighinal work on the master branch, which isn't really being developed any more. So it is OK that ecotwins has diverged. At some point we will probably want to switch the master branch to point at ecotwins rather than the old version that it currently represents. But we can discuss this. My main concern is that I don't know if all the tests etc. that we create for the master branch have been ported to the ecotwins version.

**Comment by nickmalleson** [comment]
@dabreegster I am guessing this isn't relevant any more so closing the pull request, but please re-open if needed.

**Comment by dabreegster** [comment]
Yeah, we've settled on https://github.com/dabreegster/spc for the data prep stage. I'll clean up the old issues I filed here too, now that it's clear the branches are meant to all diverge. :)

**Pull request closed without merging**
