### PR TITLE
Overweight scenario

### PR DESCRIPTION
**Pull request by spoonerf**
Added health data with new function for calculating individuals mortality risk and a multiplier to make overweight people more likely to be symptomatic

### CODE REVIEW

**Comment by nickmalleson** [comment]
@spoonerf this is failing some tests, I've not looked into yet, can you get them to pass locally? If not let me know and I can have a go this afternoon - maybe it's worth getting them to pass before mergin?

**Comment by spoonerf** [comment]
Not sure why they are failing - it seems that the python tests are falling down on this:

```
E   KeyError: 'area'

```
Which happens seven times in the python tests.

```
ERROR tests/test_microsim_model.py::test_add_home_flows - KeyError: 'area'
ERROR tests/test_microsim_model.py::test_read_school_flows_data - KeyError: '...
ERROR tests/test_microsim_model.py::test_read_msm_data - KeyError: 'area'
ERROR tests/test_microsim_model.py::test_change_behaviour_with_disease - KeyE...
ERROR tests/test_microsim_model.py::test_update_venue_danger_and_risks - KeyE...
ERROR tests/test_microsim_model.py::test_hazard_multipliers - KeyError: 'area'
ERROR tests/test_microsim_model.py::test_step - KeyError: 'area'

```

Not sure why this is error is coming up though.

**Comment by nickmalleson** [comment]
@spoonerf this can happen if the names of the columns in the input data change and the code can no longer find the column. Are the column names identical? Is there an 'area' column in the new data? If there is I'll look further, it's an odd error

**Comment by spoonerf** [comment]
@nickmalleson There are some extra column names - the health ones:  "cvd", "diabetes", "bloodpressure", "BMIvg6", "BMI_healthier". 

The area column is still in there and is the first column, but I wonder if something has gone funny with the formatting somehow as this is also in the error feedback:

```
________________ ERROR at setup of test_read_school_flows_data _________________

self = Index(['ID', 'ï»¿area', '_hid', '_pid', 'Sex', 'Age1', 'age', 'soc2010',
       'punknown', 'phome', 'pworkhome', 'pwo...port', 'pnothome',
       'phometot', 'pmwalk', 'pmcycle', 'pmprivate', 'pmpublic', 'pmunknown'],
      dtype='object') 

```
And it does look as if there is something odd going on with the area column.

**Comment by nickmalleson** [comment]
Yeah I spotted that. It looks like maybe some whitespace has been added before the word 'area' somewhere. But I searched microsim_model.py and the *.py files in the tests directory in the `overweight_scenario` on github but couldn't see where the error could have crept in. Could you search the files on your local copy? I'd look for all occurences of 'area' and see if any of them have a space before them or something. If that still doesn't reveal anything I'll pull the `overweight_scenario` branch and look myself

**Comment by spoonerf** [comment]
I'm wondering if there is something missing from the dummy_data folder on here? I only have the output folder in there with a 0 and 1 run folder in.  It looks as if that is where the tests are set to read in something from? @nickmalleson @nnelissen

**Comment by nnelissen** [comment]
@spoonerf There should be .csv and .pickle files in those folders. They seem to be here on github but maybe they didn't get copied to your local version? I had some issues where I thought a file from master had been pulled and merged without errors but it was still an old version locally (in the end I downloaded the file from github and manually replaced it).

**Comment by spoonerf** [comment]
@nnelissen  I have individual and retail pickle and csv files, should there be any others? Perhaps it is something else!

**Comment by nickmalleson** [comment]
I'll give try to get this working locally this afternoon

**Comment by spoonerf** [comment]
Thanks @nickmalleson 

I was having trouble reading in the BMI csv in the microsim_model.py and was getting this error:

```
pd.read_csv("Devon_simulated_TU_keyworker_health.csv")
Traceback (most recent call last):
  File "pandas/_libs/parsers.pyx", line 1129, in pandas._libs.parsers.TextReader._convert_tokens
  File "pandas/_libs/parsers.pyx", line 1253, in pandas._libs.parsers.TextReader._convert_with_dtype
  File "pandas/_libs/parsers.pyx", line 1268, in pandas._libs.parsers.TextReader._string_convert
  File "pandas/_libs/parsers.pyx", line 1458, in pandas._libs.parsers._string_box_utf8
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x96 in position 28: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/fionaspooner/opt/anaconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 676, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/Users/fionaspooner/opt/anaconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 454, in _read
    data = parser.read(nrows)
  File "/Users/fionaspooner/opt/anaconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 1133, in read
    ret = self._engine.read(nrows)
  File "/Users/fionaspooner/opt/anaconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 2037, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 859, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 874, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 951, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 1083, in pandas._libs.parsers.TextReader._convert_column_data
  File "pandas/_libs/parsers.pyx", line 1136, in pandas._libs.parsers.TextReader._convert_tokens
  File "pandas/_libs/parsers.pyx", line 1253, in pandas._libs.parsers.TextReader._convert_with_dtype
  File "pandas/_libs/parsers.pyx", line 1268, in pandas._libs.parsers.TextReader._string_convert
  File "pandas/_libs/parsers.pyx", line 1458, in pandas._libs.parsers._string_box_utf8
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x96 in position 28: invalid start byte
```
To get around this I changed the command to:

```
pd.read_csv("Devon_simulated_TU_keyworker_health.csv",encoding = "unicode_escape")

```
This seemed to work but is perhaps where the error is creeping in.

**Comment by nickmalleson** [comment]
@spoonerf when I run these tests locally I get an error because the tests can't find the synthetic population file. This may be the problem underneath the thing about the 'area' key:

```
E               FileNotFoundError: [Errno 2] No such file or directory: '/Users/nick/research_not_syncd/git_projects/RAMP-UA/tests/dummy_data/devon-tu_health/Devon_simulated_TU_keyworker_health_bmi.csv'
```

The problem is, you've added a new file `Devon_simulated_TU_keyworker_health_bmi.csv` but haven't made a new file for the tests. So long as the old file has all of the old columns plus some new ones I think the easiest way to fix this is to do what we discussed last week: 

1. delete the old csv file (Devon_simulated_TU_keyworker_health.csv)
2. rename the new file (Devon_simulated_TU_keyworker_health_bmi.csv) so that it has the name of the old one. 

This also means that git lfs will automatically merge in the new file. Do you want me to try that? I don't want to break anything on your branch

**Comment by spoonerf** [comment]
Hi @nickmalleson that would be great if you could. Sorry don't think I have got my head around the git lfs stuff yet. I thought I had done those steps but something clearly didn't work! Thanks!

**Comment by nickmalleson** [comment]
Sorry ignore my last comment, I think you'd done it all correctly. I hadn't pulled the branch properly. I think I have fixed it now though in https://github.com/Urban-Analytics/RAMP-UA/commit/7bad83a9d87bcd82803f4c3c308333c8b263b699 . I took out the line that forced a particular encoding when the file was being read in: https://github.com/Urban-Analytics/RAMP-UA/blob/751a389586337e39ad9b5896e4857fb13b2c425a/microsim/microsim_model.py#L425 and saved the file in utf-8 encoding and now it seems to work. The area column is the first to be read in and I think that the encoding was inserting a weird character at the start of the file, hence the weird 'area' key. So you did everything right, I'm not sure what caused the area. Hopefully all ok now though

**Comment by nickmalleson** [comment]
all done, i deleted the branch. If this happens again hopefully it will be easy to solve now that we know how to. Blame Karyns weird PSM program :-)

**Comment by spoonerf** [comment]
Hooray! Thank you 😊

**Pull request merged**
